### ISSUE TITLE
Not able to open license agreement link

### ISSUE THREAD

**Issue by sumeet-tiwari-samespace** [line/line-bot-sdk-go#290] opened 2021-09-21 05:38 UTC
not able to open license agreement link
Loading forever
https://access.line.me/dialog/bot/botUseAgreement?redirectUri=android-app%3A%2F%2Fjp.naver.line.android%2Flinecallback%2Fcustomtabs%2FbotUseAgreement%3Fstate%3D297813397&agreed=false&lineApplication=ANDROID%2011.16.2&lang=en&region=IN

**Comment by tkgauri** [comment] 2021-09-28 06:47
Hello,
We checked the behaviour on our side and found no issues. Also since this issue is not related to bot-sdk repository, we will close this issue for now. You can submit your question with more details like OS version and reproduction steps on our [community Q&A website](https://www.line-community.me/en/questions).

**Closed by tkgauri** 2021-09-28 06:47 UTC
Labels: bug
