### ISSUE TITLE
Is `limit.max` optional?

### ISSUE THREAD

**Issue by kyu-suke** [line/line-bot-sdk-go#466] opened 2024-07-18 07:47 UTC
## System Informations

* Go version: go1.22.5 darwin/arm64
* OS: macOS 14.4.1

## Current Behavior
According to [send-narrowcast-message](https://developers.line.biz/en/reference/messaging-api/#send-narrowcast-message), `max` and `upToRemainingQuota` are optional. But `Max` field in `Limit` is defined ``Max int32 `json:"max"``. As a result, when `Max` is defined zero value, it isn't defined.

If `Limit` is defined like below.
```golang
limit := &messaging_api.Limit{
  UpToRemainingQuota: true,
}
```
The result of `json.MarshalI` value is like this.
```
{
    "max": 0,
    "upToRemainingQuota": true
}
```

## Expected Behavior
It may be needed to add `omitempty`. If this approach is acceptable, I would like to proceed with submitting a pull request. Please let me know if there are any concerns or suggestions for improvement.

```
type Limit struct {
	Max int32 `json:"max,omitempty"`
	UpToRemainingQuota bool `json:"upToRemainingQuota"`
}
```
The value expected is like this.
```
{
    "upToRemainingQuota": true
}
```

## Steps to Reproduce
```golang
limit := &messaging_api.Limit{
  UpToRemainingQuota: true,
}
l, _ := json.MarshalIndent(limit, "", "    ")
fmt.Println(string(l))
```

**Comment by habara-k** [comment] 2024-08-08 02:53
Thank you for using the line-bot-sdk-go.

Thank you for your report. We have confirmed the behavior on our end as well. The Limit.max should allow null (as it has a different meaning from int 0), so omitempty should be added. Otherwise, it is not possible to use the Limit object with the sdk-go because the API does not accept max=0 in the request.

We believe this behavior should be fixed. It would be greatly appreciated if you could create a PR for the fix. Thank you very much for your cooperation.

**Closed** 2024-10-30 05:46 UTC
Labels: bug
