### ISSUE TITLE
LINE app (android) can not retrieve the audio file

### ISSUE THREAD

**Issue by cention-sany** [line/line-bot-sdk-go#30] opened 2016-11-03 01:14 UTC
Hi, I not sure if this is the right platform for me to voice this problem. I used Golang line-bot-sdk-go (Messaging API) send audio to my LINE app through a server (Apache server). But my LINE phone app (android) can not play the audio with error message: _"Unknown Error. Please wait a moment and try again."_ From the Apache SSL log, Apache server replied 400 response code which is bad request. It seem like the LINE audio retrieval code can not establish a proper TLS connection with my Apache server. I also tried replace my Apache server with Golang server (HTTP/1.1 and HTTP2) also can not get a proper connection with the audio request where the Golang ServeHTTP(http.ResponseWriter, *http.Request) is never get call though the TCP connection is there. The audio file I sent actually created from my LINE app which received by my Golang application. Note: the path that I sent using the Messaging API is a correct path because simply using Chrome/curl I can get the audio file with 200 response code. And I don't think is the audio file content issue also because the HTTP connection not reach the code opening the audio file.

I mentioned only audio attachment because image and video attachment both successfully sent to my LINE app. If I am in the wrong place to ask question on this problem then you can point me the right place to do so?

**Comment by GuitarSucks** [comment] 2016-11-08 10:37
@cention-sany 
If it was related to TLS connection you will have error with video or image also.
Older LINE App versions before 6.7.1 had a parameter added to the GET request of audio file. This was not proper way to request a file from client which was changed in 6.7.1 . 
Can you check if your are receiving extra parameter in the GET request from client side?

**Comment by cention-sany** [comment] 2016-11-09 00:08
@GuitarSucks, my LINE app version (Android) is 6.8.2. From my Apache log, which has following format:
`<IP> - - <Date time timezone> "<GET or POST> <URI> <HTTP version>" <Response code> <total bytes>`
The URI string has the correct request URI as expected from my code (the same URI I sent to the LINE Messaging API). This URI string should includes any request parameter if there is any which there isn't any for my case. I not sure if there is any better way to check it. Do let me know how I can do better in checking it. The request do not get pass into my application and was rejected by my Apache server which acted as reverse proxy with Response code 400. As I mentioned, I did try replace the Apache server with a simple debug Golang server as below:
```
package main

import (
	"crypto/tls"
	"log"
	"net"
	"net/http"
	"net/http/httputil"
)

const (
	certPath   = "cert.pem"
	keyPath    = "key.pem"
	listenAddr = ":443"
)

var (
	useHTTP1 map[string]func(*http.Server, *tls.Conn,
		http.Handler) = map[string]func(*http.Server, *tls.Conn, http.Handler){}
	useHTTP2 map[string]func(*http.Server, *tls.Conn, http.Handler) = nil
)

func handler(w http.ResponseWriter, req *http.Request) {
	hdrs, err := httputil.DumpRequest(req, false)
	if err != nil {
		log.Println("Error in dump request:", err)
		log.Println("req:", req)
	} else {
		log.Print("HTTP Header data:\n", string(hdrs))
	}
	w.Header().Set("Content-Type", "text/plain")
	w.Write([]byte("This is an example server.\n"))
}

func connStateHandler(c net.Conn, cs http.ConnState) {
	log.Println("connect state:", cs.String(), "From:", c.RemoteAddr().String())
}

func main() {
	http.HandleFunc("/", handler)
	s := &http.Server{
		Addr:         listenAddr,
		ConnState:    connStateHandler,
		TLSNextProto: useHTTP1,
	}
	log.Println("About to listen to", listenAddr)
	err := s.ListenAndServeTLS(certPath, keyPath)
	log.Fatal(err)
}
```
The result of this Golang server log is that there isn't any log from handler func but I can see the connStateHandler of "new", "active" then "close" when I click play the sound in my LINE app. I not sure how I can get the request parameter from this Golang server because the handler func is never get trigger at all. Do let me know if any better way for me to debug this Golang server. NOTE: If I simply run command  `curl -s -D - <URI> -o /dev/null` to this Golang server I can get "new", "active", handler log, "idle" and "close" logging.

**Comment by GuitarSucks** [comment] 2016-11-14 11:39
@cention-sany 
We are checking this, but our environment is different from yours.
At this point we cant reproduce this.

**Comment by cention-sany** [comment] 2016-11-15 01:31
I manually contructed the link for this testing as below:
https://43.cust.cention.se/ng/line/attachment/816/307/audio.m4a
Maybe it can help for your side. This link sent into my LINE app which it will give the same error as picture below:
![test](https://cloud.githubusercontent.com/assets/12839593/20289666/0e3a1c06-ab16-11e6-9355-27dbb9a9a909.jpeg)

**Comment by mrmaakun** [comment] 2016-11-17 06:42
Hello @cention-sany 

I was able to reproduce this issue by sending an m4a audio file that is hosted on a golang server via the messaging API and then attempting to play it in the LINE Android App. I was able to play the audio file in the iOS LINE App and access it using Chrome and curl.

Our Android team will look into this issue. We will let you know if they come back with something.

Just for clarification, the file in the link in the above post that you constructed for testing is being served by a golang server, correct?

**Comment by cention-sany** [comment] 2016-11-17 06:46
@mrmaakun to be exact, 43.cust.cention.se has Apache acting as reverse proxy and handle the TLS portion and redirect HTTP request to a golang HTTP server.

**Comment by davisray2909** [comment] 2017-02-24 19:57
Hi @cention-sany , @GuitarSucks , and @mrmaakun 
Im also having the same error using Azure server. Do you guys found any solutions yet?
Thanks in advance.

**Comment by letrungkien211** [comment] 2017-03-31 03:24
I also have the same errors when using Azure Storage. Does Line have plan to fix this?

**Comment by davisray2909** [comment] 2017-03-31 03:42
@letrungkien211 I guess our only option is either using another Storage or wait until Line come up with better solution.

**Comment by letrungkien211** [comment] 2017-03-31 03:48
@davisray2909 That's really sad. I faced similar issue with Video as well. Our team actually contacted Line directly last year but they basically refuse to take action. When I saw this post, I had some hope :(. 
Right now we're using Apache in Linux VM as a work around, but Azure storage is just a lot better in term of simplicity and scalibility.

**Comment by cention-sany** [comment] 2017-03-31 04:05
@letrungkien211 I have the almost same issue with Video can not be played but only iOS LINE, Android no issue. Not sure if you facing the same problem or not.

**Comment by letrungkien211** [comment] 2017-03-31 04:13
@davisray2909 Honestly, I don't remember exactly anymore. Maybe it was the same to me.
FYI, I tried multiple solutions:
Create Java Apache server on windows
Use Azure Storage directly
Create Azure C# webapi 
Create node-js server in Windows
...
Each of the above solution only make Audio/Video work on either android or iphone. If a solution works on iphone, it doesn't on android and vice versa. I finally gave up months ago.

**Comment by davisray2909** [comment] 2017-03-31 04:15
@letrungkien211 @cention-sany Exactly the same problem.

**Comment by fataelislami** [comment] 2017-06-14 23:26
for the solution , i choose to upload on site google, and copy the direct link into line API 
hope it help

**Comment by saurabhabh** [comment] 2018-01-23 12:26
@letrungkien211 @GuitarSucks @mrmaakun Any update on this issue? I am facing the same issue on Azure server. As stated above it works fine if I upload it to the google server or a dropbox.

**Comment by tokuhirom** [comment] 2018-06-28 06:12
@GuitarSucks any updates?

**Comment by GuitarSucks** [comment] 2018-10-11 04:19
We will check this issue again. Sorry for the delay

**Comment by letrungkien211** [comment] 2018-11-30 01:07
@GuitarSucks Any update? We are going to send dynamically created videos to users at Christmas. We'd like to upload them to Azure storage for scalability. This is blocking issue.

**Comment by letrungkien211** [comment] 2018-12-01 09:33
Hi, FYI
I've tested and confirmed that when uploading audio (m4a) + video (mp4) to Azure blob storage, the following devices can play them
1. Iphone 7
2. Xperia XZ
3. Huwei P20 Lite
I am asking all our team members to test on more devices and will update this post accordingly.
I really hope this has been completely resolved. Thanks!

**Comment by tkgauri** [comment] 2019-04-12 06:37
Hello,

Sorry for taking long to respond to this issue.

We have tested that audio(m4a) can be played successfully on android/iOS devices.
Devices used for testing: iPhone X, Pixel 3

Also, as per letrungkien211's comment dated Dec 1st 2018, audio can be played successfully on other android/iOS devices as well. Refer comment for device details.

For now, we are closing this issue.

If you face similar issue in future please post your question to our community website:
https://www.line-community.me/questions

Thanks!

**Closed** 2019-04-12 06:37 UTC
Labels: question
